# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: 'write'  

jobs:
  # Task 1: Build Java Application using Maven
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build JAR with Maven
      run: mvn compile

    # Configure Workload Identity Federation via a credentials file.
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        create_credentials_file: true
        workload_identity_provider: 'projects/198122355685/locations/global/workloadIdentityPools/githubactions/providers/github'
        service_account: 'ksyservacc@my-second-project-418213.iam.gserviceaccount.com'
        token_format: "access_token"
    
    - id: 'gcloud'
      name: 'Auth login & Build Function'
      run: |-             
        gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}" --no-user-output-enabled        
        gcloud functions deploy java-http-function2 \
          --gen2 \
          --entry-point=functions.HelloWorld \
          --runtime=java17 \
          --region=us-central1 \
          --source=./httpFunction \
          --trigger-http \
          --allow-unauthenticated \
          --ingress-settings=internal
